import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from "./Redux/StoreProvider";
import Header from "./Header";

export const metadata: Metadata = {
  title: "Nextjs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="bg-white-400">
          <header>
            <Header />
          </header>
          <main className="mr-16 ml-16 mb-16 mt-none shadow md:shadow-2xl p-6">
            {children}
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
