import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from "./Redux/StoreProvider";

export const metadata: Metadata = {
  title: "Nextjs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="bg-white">{children}</body>
      </html>
    </StoreProvider>
  );
}
